version: '3.4'

services:
  productsdb:
    image: postgres
  basketdb:
    image: postgres
  distributedcahce:
    image: redis
  products.api:
    image: ${DOCKER_REGISTRY-}productsapi
    build:
      context: .
      dockerfile: Services/Catalog/Products.API/Dockerfile

  shoppingcart.api:
    image: ${DOCKER_REGISTRY-}shoppingcartapi
    build:
      context: .
      dockerfile: Services/ShoppingCart/ShoppingCart.API/Dockerfile

volumes:
  postgres_product:
  postgres_basket:

